#!/bin/bash
# ==============================================================================
# Neovim Module - Neovim with NvChad configuration
# ==============================================================================

# ------------------------------------------------------------------------------
# Install Neovim (if not already installed by tools module)
# ------------------------------------------------------------------------------
install_neovim_base() {
    log "INFO" "Verificando Neovim..."

    if [[ -d "$HOME/nvim-linux64" ]] || command -v nvim &>/dev/null; then
        log "SUCCESS" "Neovim ya está instalado."
        return 0
    fi

    local temp_tar="/tmp/nvim-linux64.tar.gz"

    log "INFO" "Descargando Neovim..."
    wget -q "https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz" -O "$temp_tar"

    log "INFO" "Extrayendo Neovim..."
    tar xzf "$temp_tar" -C "$HOME"
    rm -f "$temp_tar"

    # Add to PATH if not already present
    if ! grep -q "nvim-linux64/bin" ~/.zshrc 2>/dev/null; then
        echo 'export PATH="$HOME/nvim-linux64/bin:$PATH"' >> ~/.zshrc
    fi

    log "SUCCESS" "Neovim instalado correctamente."
}

# ------------------------------------------------------------------------------
# Install NvChad configuration
# ------------------------------------------------------------------------------
install_nvchad() {
    log "INFO" "Instalando NvChad..."

    local nvchad_dir="$HOME/.config/nvim"

    # Check if NvChad is already installed
    if [[ -d "$nvchad_dir" ]] && [[ -f "$nvchad_dir/init.lua" ]]; then
        # Check if it's actually NvChad
        if grep -q "nvchad" "$nvchad_dir/init.lua" 2>/dev/null; then
            log "SUCCESS" "NvChad ya está instalado."
            return 0
        fi
    fi

    # Backup existing config if exists
    if [[ -d "$nvchad_dir" ]]; then
        local backup_dir="$HOME/.config/nvim.backup.$(date +%Y%m%d_%H%M%S)"
        log "INFO" "Respaldando configuración existente a $backup_dir"
        mv "$nvchad_dir" "$backup_dir"
    fi

    # Clone NvChad
    log "INFO" "Clonando NvChad (rama por defecto)..."
    git clone https://github.com/NvChad/NvChad "$nvchad_dir" --depth 1

    if [[ ! -d "$nvchad_dir" ]]; then
        log "ERROR" "Error al clonar NvChad."
        return 1
    fi

    log "SUCCESS" "NvChad instalado correctamente."

    # Install NvChad dependencies
    log "INFO" "Instalando plugins de NvChad (primera ejecución)..."
    "$HOME/nvim-linux64/bin/nvim" -c 'autocmd User LazyInstall qall' -c 'lua require("nvchad.plugins").install()' 2>/dev/null || true

    log "SUCCESS" "NvChad configurado. Ejecuta 'nvim' para completar la instalación de plugins."
}

# ------------------------------------------------------------------------------
# Configure custom NvChad settings
# ------------------------------------------------------------------------------
configure_nvchad() {
    log "INFO" "Configurando personalizaciones de NvChad..."

    local nvchad_base="$HOME/.config/nvim"
    local lua_dir="$nvchad_base/lua/custom"

    # Create custom directory if not exists
    mkdir -p "$lua_dir"

    # Create chadrc.lua if not exists
    local chadrc="$lua_dir/chadrc.lua"
    if [[ ! -f "$chadrc" ]]; then
        cat > "$chadrc" << 'EOF'
-- NvChad Custom Configuration
-- Generated by Linux Setup Toolkit

local M = {}

M.ui = {
    theme = "catppuccin",

    -- Statusline
    statusline = {
        theme = "minimal",
        separator_style = "default",
    },

    -- Tabline
    tabline = {},

    -- NvChad UI theme
    theme_toggle = 2,

    -- Hide ui elements
    hide = {
        cmd = false,
        tab = false,
    },
}

M.base46 = {
    hl_override = {},
}

return M
EOF
        log "SUCCESS" "chadrc.lua creado con configuración base."
    fi

    # Create init.lua if not exists (should exist from NvChad)
    local init_lua="$lua_dir/init.lua"
    if [[ ! -f "$init_lua" ]]; then
        cat > "$init_lua" << 'EOF'
-- NvChad Custom Init
-- Generated by Linux Setup Toolkit

-- Load base NvChad config
require "nvchad"

-- Add custom mappings, autocmds, etc.
require "custom.mappings"
require "custom.autocmds"
EOF
        log "SUCCESS" "init.lua personalizado creado."
    fi

    # Create mappings.lua if not exists
    local mappings="$lua_dir/mappings.lua"
    if [[ ! -f "$mappings" ]]; then
        cat > "$mappings" << 'EOF'
-- Custom Key Mappings
local M = {}

M.keys = {}

-- Add your custom mappings here
-- Example:
-- table.insert(M.keys, {
--     n = { "<leader>ff", "<cmd>Telescope find_files<cr>", "Find Files" }
-- })

return M
EOF
        log "SUCCESS" "mappings.lua creado."
    fi

    # Create autocmds.lua if not exists
    local autocmds="$lua_dir/autocmds.lua"
    if [[ ! -f "$autocmds" ]]; then
        cat > "$autocmds" << 'EOF'
-- Custom Autocommands
local M = {}

M.autocmds = {}

-- Add your custom autocmds here

return M
EOF
        log "SUCCESS" "autocmds.lua creado."
    fi

    log "SUCCESS" "Configuración de NvChad completada."
}

# ------------------------------------------------------------------------------
# Full NvChad installation
# ------------------------------------------------------------------------------
install_nvchad_full() {
    install_neovim_base
    install_nvchad
    configure_nvchad
}

# ------------------------------------------------------------------------------
# Uninstall NvChad configuration
# ------------------------------------------------------------------------------
uninstall_nvchad() {
    log "INFO" "Desinstalando NvChad..."

    local nvchad_dir="$HOME/.config/nvim"

    if [[ -d "$nvchad_dir" ]]; then
        # Check if it's NvChad
        if grep -q "nvchad" "$nvchad_dir/init.lua" 2>/dev/null; then
            mv "$nvchad_dir" "$HOME/.config/nvim.backup.$(date +%Y%m%d_%H%M%S)"
            log "SUCCESS" "NvChad desinstalado (respaldado)."
        else
            log "INFO" "La configuración de nvim no parece ser NvChad."
            mv "$nvchad_dir" "$HOME/.config/nvim.backup.$(date +%Y%m%d_%H%M%S)"
            log "SUCCESS" "Configuración de nvim respaldada."
        fi
    else
        log "INFO" "NvChad no está instalado."
    fi
}

# ------------------------------------------------------------------------------
# Uninstall Neovim binary
# ------------------------------------------------------------------------------
uninstall_neovim() {
    log "INFO" "Desinstalando Neovim..."

    if [[ -d "$HOME/nvim-linux64" ]]; then
        rm -rf "$HOME/nvim-linux64"
        # Remove from PATH in zshrc
        sed -i '/nvim-linux64\/bin/d' ~/.zshrc 2>/dev/null || true
        log "SUCCESS" "Neovim desinstalado."
    else
        log "INFO" "Neovim no está instalado."
    fi
}

# ------------------------------------------------------------------------------
# Uninstall complete NvChad setup
# ------------------------------------------------------------------------------
uninstall_nvchad_full() {
    log "INFO" "Desinstalando NvChad completo..."

    uninstall_nvchad
    uninstall_neovim

    log "SUCCESS" "NvChad completo desinstalado."
}
